### PR TITLE
Add postinstall script to fetch data. Update doc.

### PR DESCRIPTION
**Pull request by Tiagojdferreira**

### CODE REVIEW

**Comment by Tiagojdferreira** [comment]
I have added a postinstall step to the package.json, this way the script is run to update the database. I have also updated the docs.

**Comment by rexxars** [comment]
This looks great! I'm a bit skeptical to running the script on postinstall though - it makes deployment and updating dependencies etc a bit weird. If you rename the npm script to something else and document the use/setup of it, I'd happily merge this.

**Comment by Tiagojdferreira** [comment]
Updated. Let me know if you want me to change anything.

**Comment by kbrabrand** [comment]
:+1:

**Pull request merged**
