### PR TITLE
Add name of component and author at top of component-info

### LINKED ISSUE #15: Display component author's username
It'd be nice if I could tell, at a glance, whether or not a component like [reactfire](http://react-components.com/component/reactfire) was released by firebase or a third party. As is, I have to click through to the homepage or github to figure that out.

### PR DESCRIPTION
**Pull request by Tiagojdferreira**
This should close #15 .

### CODE REVIEW

**Comment by rexxars** [comment]
Thanks! Will check it out later and merge if it looks good (UI-wise)

**Comment by Tiagojdferreira** [comment]
@rexxars ping

**Comment by rexxars** [comment]
Looking into it now! Sorry :-)

**Comment by rexxars** [comment]
This looks pretty good, but maybe we could put `by <author>` on a new line below the name of the module, with a slightly smaller font size? Takes a bit too much attention right now, in my opinion. Thoughts, @kbrabrand ?

Here's a screenshot of how it looks currently:

screenshot from 2015-10-13 17 42 50

**Comment by Tiagojdferreira** [comment]
screen shot 2015-10-13 at 23 11 13

Do you prefer it like this ?

**Comment by rexxars** [comment]
Yeah, that looks good. Thanks!

**Pull request merged**
